services:
  ide:
    image: ghcr.io/kelvin-keegen/code-server:latest
    container_name: code-server
    user: "coder"
    ports:
      - "9090:8080"
    environment:
      - JAVA_HOME=/home/coder/.sdkman/candidates/java/current
      - MAVEN_HOME=/home/coder/.sdkman/candidates/maven/current
      - PATH=/home/coder/.sdkman/candidates/java/current/bin:/home/coder/.sdkman/candidates/maven/current/bin:$PATH
      - PASSWORD=your_password_here
    volumes:
      - my_workspace:/my_workspace
      - server_conf:/home/coder
    restart: unless-stopped
volumes:
  my_workspace:
  server_conf:
