name: Build and Publish Dev Docker Image

on:
  workflow_run:
    workflows:
      - Validate Docker Image
    branches:
      - feature/*
      - update/*
    types:
      - completed

jobs:
  build-and-release-dev-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Extract VERSION from Dockerfile
        id: extract-version
        run: |
          VERSION=$(grep -m 1 '^ARG VERSION=' Dockerfile | cut -d '=' -f2)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:dev
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.event.workflow_run.head_sha }}

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
